paths:
  /api/products/:
    get:
      summary: Muestra todos los productos disponibles.
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos con exito.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor.

  /api/products/{pid}:
    get:
      summary: Muestra un producto de interes segun el ID ingresado.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto buscado.
          schema:
            type: String
      responses:
        "200":
          description: El producto fue encontrado con exito.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor.

    put:
      summary: Permite actualizar la informacion de un producto segun su ID.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description:  ID del producto a modificar.
          schema:
            type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProductRequest"

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        category:
          type: String
          description: Categoría del producto
        availability:
          type: Number
          description: Disponibilidad del producto
        owner:
          type: String
          description: Propietario del producto (por defecto, 'admin')
      example:
        name: "Producto 1"
        description: "Este trata de un producto de ejemplo"
        price: 200
        category: "Categoria de ejemplo"
        availability: 5
        owner: "admin"

    UpdateProductRequest:
      type: object
      properties:
        name:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        category:
          type: String
          description: Categoría del producto
        availability:
          type: Number
          description: Disponibilidad del producto
      example:
        name: "Ejemplo de actualizacion"
        description: "Descripción del ejemplo de actualizacion"
        price: 500
        category: "Nueva Categoría"
        availability: 10